image: node:6.9.4

clone: 
  depth:
    full
pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script: 
            - npm install
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
